name: CD Workflow Frontend

on:
  workflow_run:
    workflows: ["CI Workflow Frontend"]
    types:
      - success

jobs:
  cd-frontend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Vérifier le code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de Node.js
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'

      # Étape 3 : Installation des dépendances
      - name: Installation des dépendances
        run: npm install
        working-directory: front

      # Étape 4 : Construction du projet
      - name: Construction du projet
        run: npm run build
        working-directory: front

      # Étape 5 : Connexion à Docker Hub
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 6 : Construction et push de l'image Docker
      - name: Construction et push de l'image Docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: front
          file: front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:latest
