name: CD Workflow Backend

on:
  push:
    branches:
      - main

jobs:
  cd-backend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Vérifier le code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      # Étape 3 : Construction du projet avec Maven
      - name: Construction du projet avec Maven
        run: mvn clean install -DskipTests
        working-directory: back

      # Étape 4 : Connexion à Docker Hub
      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Étape 5 : Construction et push de l'image Docker
      - name: Construction et push de l'image Docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: back
          file: back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/bobapp-backend:latest

      # Étape 6 : Vérification des images Docker
      - name: List les images Docker
        run: docker images