name: CI Workflow Backend

on:
  push:
    branches:
      - main
    paths:
      - 'back/**'
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - 'back/**'

jobs:
  ci-backend:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Vérifier le code
        uses: actions/checkout@v4

      # Étape 2 : Configuration de JDK 17
      - name: Configurer JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      # Étape 3 : Cache des packages SonarCloud
      - name: Mettre en cache les packages SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      

      # Étape 4 : Cache des packages Maven
      - name: Mettre en cache les packages Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Étape 5 : Build et analyse avec SonarCloud
      - name: Build et analyse avec SonarCloud
        working-directory: back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
        run: |
          mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=Backend-P10-Gerez-Un-Projet-Collaboratif \
          -Dsonar.projectName=Backend-P10 \
          -Dsonar.organization=chrystalmoi

      # Étape 6 : Upload du rapport JaCoCo
      - name: Upload du rapport JaCoCo
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: back/target/site/jacoco/